### ISSUE TITLE
Serve OpenGraph tags to get an image and description when links to your page are embedded in other apps

### ISSUE THREAD

**Issue by joshhayes-sheen-wf** [salt-today/salttoday#77] opened 2019-06-04 15:08 UTC
For example, from Github:

```html
<meta property="og:image" content="https://avatars2.githubusercontent.com/u/48812385?s=400;v=4" />
<meta property="og:site_name" content="GitHub" />
<meta property="og:type" content="object" />
<meta property="og:title" content="salt-today/salttoday" />
<meta property="og:url" content="https://github.com/salt-today/salttoday" />
<meta property="og:description" content="Scrapes Sootoday and displays statistics about users and comments. - salt-today/salttoday" />
```

Which results in something like

![og-embed](https://user-images.githubusercontent.com/1669293/58890512-c47ad700-86b8-11e9-977e-20b9a3695ec6.png)

Currently instead we get

![no-og](https://user-images.githubusercontent.com/1669293/58890637-0146ce00-86b9-11e9-8771-7919e478dc3c.png)

**Comment by xTVaser** [comment] 2019-06-04 15:19
Duplicate of #57

**Closed as completed** 2019-06-04 19:49 UTC
